// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using System;
using System.Collections.Generic;

namespace EES.Infrastructure.Log;

/// <summary>
/// 接口请求记录表
/// </summary>
public partial class ApiLog: LogEntityBase
{
  
    /// <summary>
    /// 用户id
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// 平台
    /// </summary>
    public string Platform { get; set; }

    /// <summary>
    /// 接口请求类型   post  或者get
    /// </summary>
    public string RequestType { get; set; }

    /// <summary>
    /// 接口名
    /// </summary>
    public string ApiRoute { get; set; }

    /// <summary>
    /// 请求url
    /// </summary>
    public string RequestUrl { get; set; }

    /// <summary>
    /// 请求的header数据
    /// </summary>
    public string RequestHeader { get; set; }

    /// <summary>
    /// 请求参数的querystring
    /// </summary>
    public string RequestQuery { get; set; }

    /// <summary>
    /// 请求参数的body
    /// </summary>
    public string RequestBody { get; set; }

    
    public string TraceId { get; set; }

    /// <summary>
    /// 请求时间
    /// </summary>
    public DateTime? RequestTime { get; set; }

    /// <summary>
    /// 响应参数
    /// </summary>
    public string Response { get; set; }

    /// <summary>
    /// 总计耗时（毫秒）
    /// </summary>
    public long TimeConsumption { get; set; }

}