// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using System;
using System.Collections.Generic;

namespace EES.Infrastructure.Log;

/// <summary>
/// 数据审计表- 仅记录修改和删除
/// </summary>
public partial class AuditLog : LogEntityBase
{
    /// <summary>
    /// 数据库名
    /// </summary>
    public string DbName { get; set; }

    /// <summary>
    /// 表名
    /// </summary>
    public string TableName { get; set; }

    /// <summary>
    /// 业务实体名
    /// </summary>
    public string EntityName { get; set; }

    /// <summary>
    /// 对象主键id
    /// </summary>
    public long ObjectId { get; set; }

    /// <summary>
    /// 操作类型： 1 修改    -1 删除
    /// </summary>
    public int OperateType { get; set; }

    /// <summary>
    /// 修改之前的值，json
    /// </summary>
    public string OriginalValue { get; set; }

    /// <summary>
    /// 修改之后的值 , json
    /// </summary>
    public string SetValue { get; set; }

    /// <summary>
    /// 操作人
    /// </summary>
    public long OperatorId { get; set; }

    /// <summary>
    /// 操作人名称
    /// </summary>
    public string OperatorName { get; set; }

    /// <summary>
    /// 操作时间
    /// </summary>
    public DateTime? OperateTime { get; set; }

}