// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using EES.Infrastructure.Service;
using EES.Infrastructure.Tools;
using System;
using System.Collections.Generic;

namespace EES.Infrastructure.Log;

/// <summary>
/// 异常信息记录表
/// </summary>
public partial class ExceptionLog : LogEntityBase
{

    /// <summary>
    /// 异常标识
    /// </summary>
    public Guid Flag { get; set; }

    /// <summary>
    /// trace_id
    /// </summary>
    public string TraceId { get; set; }

    /// <summary>
    /// 异常提示信息
    /// </summary>
    public string Message { get; set; }

    /// <summary>
    /// 异常类型
    /// </summary>
    public string ExceptionType { get; set; }

    /// <summary>
    /// 异常的完整错误信息
    /// </summary>
    public string Text { get; set; }

    /// <summary>
    /// 堆栈信息
    /// </summary>
    public string StackTrace { get; set; }
    
    /// <summary>
    /// 异常发生的时间
    /// </summary>
    public DateTime? OccurredTime { get; set; }
  
}