// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using System;
using System.Collections.Generic;

namespace EES.Infrastructure.Log;

/// <summary>
/// 用户登录记录表
/// </summary>
public partial class LoginLog : LogEntityBase
{
    /// <summary>
    /// 用户id
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// 登录用户名
    /// </summary>
    public string UserAccount { get; set; }

    /// <summary>
    /// 用户名称
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// 登录平台
    /// </summary>
    public string LoginPlatform { get; set; }

    /// <summary>
    /// 授权token
    /// </summary>
    public string Token { get; set; }

    /// <summary>
    /// ip
    /// </summary>
    public string IpV4 { get; set; }

    /// <summary>
    /// v6ip  暂时预留
    /// </summary>
    public string IpV6 { get; set; }

    /// <summary>
    /// header里的UA标识
    /// </summary>
    public string UserAgent { get; set; }

    /// <summary>
    /// 登陆时间
    /// </summary>
    public DateTime? LoginTime { get; set; }

}