// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using System;
using System.Collections.Generic;

namespace EES.Infrastructure.Log;

/// <summary>
/// 用户操作记录表
/// </summary>
public partial class OperationLog : LogEntityBase
{
    /// <summary>
    /// 用户id
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// 用户名称
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// 批次号
    /// </summary>
    public Guid BatchId { get; set; }

    /// <summary>
    /// 操作类型 新增，修改，删除，审批，等，具体再定义
    /// </summary>
    public int OperateType { get; set; }

    /// <summary>
    /// 操作类型的文字说明
    /// </summary>
    public string OperateTypeDesc { get; set; }

    /// <summary>
    /// 操作对象的id
    /// </summary>
    public long ObjectId { get; set; }

    /// <summary>
    /// 关键字信息，比如 工单号， 仓库编号等
    /// </summary>
    public string ObjectKeywords { get; set; }

    /// <summary>
    /// 备注
    /// </summary>
    public string Remark { get; set; }

    /// <summary>
    /// 操作时间
    /// </summary>
    public DateTime? OperateTime { get; set; }

    /// <summary>
    /// 模块名字
    /// </summary>
    public string ModuleName { get; set; }

    /// <summary>
    /// 模块标识
    /// </summary>
    public string ModuleFlag { get; set; }

    /// <summary>
    /// 子模块名字
    /// </summary>
    public string SubModuleName { get; set; }

    /// <summary>
    /// 子模块标识
    /// </summary>
    public string SubModuleFlag { get; set; }

}