// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using System;
using System.Collections.Generic;

namespace EES.Modules.Ums.Entities
{
    /// <summary>
    /// 部门信息
    /// </summary>
    public partial class Department : EntityBase
    {
        /// <summary>
        /// 实例化部门实体
        /// </summary>
        /// <param name="parentId">上级部门id，没有默认为0</param>
        /// <param name="sortNumber">排序(同级别下)</param>
        /// <param name="code">编码，代号</param>
        /// <param name="name">部门名称</param>
        /// <param name="description">描述</param>
        /// <param name="imageUrl">部门图片</param>
        /// <param name="createUserId">创建者id</param>
        /// <param name="createUserName">创建者名称</param>
        public Department(long parentId, int sortNumber, string code, string name, string description, string imageUrl, long createUserId, string createUserName) : base(createUserId, createUserName)
        {
            ParentId = parentId;
            SortNumber = sortNumber;
            Code = string.IsNullOrEmpty(code) ? string.Empty : code;
            Name = name;
            Description = string.IsNullOrEmpty(description) ? string.Empty : description;
            ImageUrl = string.IsNullOrEmpty(imageUrl) ? string.Empty : imageUrl;
        }

        /// <summary>
        /// 
        /// </summary>
        protected Department() { }

        /// <summary>
        /// 数据的父级ID
        /// </summary>
        public long ParentId { get; private set; }
        /// <summary>
        /// 序号
        /// </summary>
        public int SortNumber { get; private set; }
        /// <summary>
        /// 代码编码(通常由用户指定，以关联到其他系统)
        /// </summary>
        public string Code { get; private set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; private set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; private set; }
        /// <summary>
        /// 图标的url
        /// </summary>
        public string ImageUrl { get; private set; }

        /// <summary>
        /// 部门内用户集合
        /// </summary>
        public IList<User> Users { get; set; }


        /// <summary>
        /// 修改信息
        /// </summary>
        /// <param name="parentId">修改信息</param>
        /// <param name="sortNumber">序号</param>
        /// <param name="code">编码</param>
        /// <param name="name">部门名称</param>
        /// <param name="description">描述</param>
        /// <param name="imageUrl">图片url</param>
        /// <param name="updateUserId">修改者id</param>
        /// <param name="createUserName">修改者名称</param>
        public void Modify(long parentId, int sortNumber, string code, string name, string description, string imageUrl, long updateUserId, string createUserName)
        {
            ParentId = parentId;
            SortNumber = sortNumber;
            Code = string.IsNullOrEmpty(code) ? string.Empty : code;
            Name = name;
            Description = string.IsNullOrEmpty(description) ? string.Empty : description;
            ImageUrl = string.IsNullOrEmpty(imageUrl) ? string.Empty : imageUrl;

            UpdateRecord(updateUserId, createUserName);
        }

    }
}