// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using EES.Infrastructure.Enums;
using System;
using System.Collections.Generic;

namespace EES.Modules.Ums.Entities
{
    /// <summary>
    /// 角色菜单权限表
    /// </summary>
    public partial class RoleMenus: EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="roleId"></param>
        /// <param name="menuId"></param>
        /// <param name="menuType"></param>
        /// <param name="createUserId"></param>
        /// <param name="createUserName"></param>
        public RoleMenus(long roleId, long menuId, MenuType menuType, long createUserId, string createUserName):base(createUserId, createUserName)
        {
            RoleId = roleId;
            MenuId = menuId;
            MenuType = menuType;
        }

        /// <summary>
        /// 角色id
        /// </summary>
        public long RoleId { get; private set; }
        /// <summary>
        /// 菜单id
        /// </summary>
        public long MenuId { get; private set; }

        /// <summary>
        /// 菜单类型
        /// </summary>
        public MenuType MenuType { get; private set; }

        /// <summary>
        /// 角色
        /// </summary>
        public virtual Role Role { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="roleId"></param>
        /// <param name="menuIds"></param>
        /// <param name="type"></param>
        /// <param name="createUserId"></param>
        /// <param name="createUserName"></param>
        /// <returns></returns>
        public static IEnumerable<RoleMenus> GenerateRoleMenus(long roleId, IEnumerable<long> menuIds, MenuType type, long createUserId, string createUserName)
        {
            foreach (var item in menuIds)
            {
                yield return new RoleMenus(roleId, item, type, createUserId, createUserName);
            }
        }

    }
}