// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using System;
using System.Collections.Generic;

namespace EES.Modules.Ums.Entities
{
    /// <summary>
    /// 组员
    /// </summary>
    public partial class TeamMembers : EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
        protected TeamMembers() { }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="teamId"></param>
        /// <param name="userId"></param>
        /// <param name="createUserId"></param>
        /// <param name="createUserName"></param>
        public TeamMembers(long teamId, long userId, long createUserId, string createUserName) : base(createUserId, createUserName)
        {
            TeamId = teamId;
            UserId = userId;
        }

        /// <summary>
        /// 所属班组id
        /// </summary>
        public long TeamId { get; private set; }

        /// <summary>
        /// 用户ID
        /// </summary>
        public long UserId { get; private set; }


        /// <summary>
        /// 生成实体
        /// </summary>
        /// <param name="teamId"></param>
        /// <param name="userIds"></param>
        /// <param name="createUserId"></param>
        /// <param name="createUserName"></param>
        /// <returns></returns>
        public static IEnumerable<TeamMembers> GenerateUserRoles(long teamId, IEnumerable<long> userIds, long createUserId, string createUserName)
        {
            foreach (var userId in userIds)
            {
                yield return new TeamMembers(teamId, userId, createUserId, createUserName);
            }
        }

    }
}