// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using EES.Modules.Ums.Enums;
using System;
using System.Collections.Generic;

namespace EES.Modules.Ums.Entities
{
    /// <summary>
    /// 工作组信息
    /// </summary>
    public partial class Team : EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
        protected Team() { }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="code"></param>
        /// <param name="name"></param>
        /// <param name="type"></param>
        /// <param name="factoryCode"></param>
        /// <param name="factoryName"></param>
        /// <param name="factoryId"></param>
        /// <param name="areaCode"></param>
        /// <param name="areaName"></param>
        /// <param name="areaId"></param>
        /// <param name="description"></param>
        /// <param name="createUserId"></param>
        /// <param name="createUserName"></param>
        public Team(string code, string name, TeamType type, string factoryCode, string factoryName, long factoryId, string areaCode, string areaName, long areaId, string description, long createUserId, string createUserName) : base(createUserId, createUserName)
        {
            Code = string.IsNullOrEmpty(code) ? string.Empty : code;
            Name = string.IsNullOrEmpty(name) ? string.Empty : name;
            Type = type;
            FactoryCode = string.IsNullOrEmpty(factoryCode) ? string.Empty : factoryCode;
            FactoryName = string.IsNullOrEmpty(factoryName) ? string.Empty : factoryName;
            FactoryId = factoryId;
            AreaCode = string.IsNullOrEmpty(areaCode) ? string.Empty : areaCode;
            AreaName = string.IsNullOrEmpty(areaName) ? string.Empty : areaName;
            AreaId = areaId;
            Description = string.IsNullOrEmpty(description) ? string.Empty : description;
        }

        /// <summary>
        /// 工作组编码
        /// </summary>
        public string Code { get; private set; }
        /// <summary>
        /// 工作组名称
        /// </summary>
        public string Name { get; private set; }
        /// <summary>
        /// 班组类型
        /// </summary>
        public TeamType Type { get; private set; }
        /// <summary>
        /// 工厂编码
        /// </summary>
        public string FactoryCode { get; private set; }
        /// <summary>
        /// 工厂名称
        /// </summary>
        public string FactoryName { get; private set; }
        /// <summary>
        /// 工厂id
        /// </summary>
        public long FactoryId { get; private set; }
        /// <summary>
        /// 工作区域编码
        /// </summary>
        public string AreaCode { get; private set; }
        /// <summary>
        /// 工作区域名称
        /// </summary>
        public string AreaName { get; private set; }
        /// <summary>
        /// 工作区域id
        /// </summary>
        public long AreaId { get; private set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; private set; }


        /// <summary>
        /// 修改信息
        /// </summary>
        /// <param name="code"></param>
        /// <param name="name"></param>
        /// <param name="type"></param>
        /// <param name="factoryCode"></param>
        /// <param name="factoryName"></param>
        /// <param name="factoryId"></param>
        /// <param name="areaCode"></param>
        /// <param name="areaName"></param>
        /// <param name="areaId"></param>
        /// <param name="description"></param>
        /// <param name="updateUserId"></param>
        /// <param name="updateUserName"></param>
        public void Modify(string code, string name, TeamType type, string factoryCode, string factoryName, long factoryId, string areaCode, string areaName, long areaId, string description, long updateUserId, string updateUserName)
        {
            Code = string.IsNullOrEmpty(code) ? string.Empty : code;
            Name = string.IsNullOrEmpty(name) ? string.Empty : name;
            Type = type;
            FactoryCode = string.IsNullOrEmpty(factoryCode) ? string.Empty : factoryCode;
            FactoryName = string.IsNullOrEmpty(factoryName) ? string.Empty : factoryName;
            FactoryId = factoryId;
            AreaCode = string.IsNullOrEmpty(areaCode) ? string.Empty : areaCode;
            AreaName = string.IsNullOrEmpty(areaName) ? string.Empty : areaName;
            AreaId = areaId;
            Description = string.IsNullOrEmpty(description) ? string.Empty : description;

            UpdateRecord(updateUserId, updateUserName);
        }

        /// <summary>
        /// 修改工厂名称或者编码
        /// </summary>
        /// <param name="factoryCode"></param>
        /// <param name="factoryName"></param>
        public void ModifyFactoryInfo(string factoryCode, string factoryName)
        {
            FactoryCode = string.IsNullOrEmpty(factoryCode) ? string.Empty : factoryCode;
            FactoryName = string.IsNullOrEmpty(factoryName) ? string.Empty : factoryName;

        }

        /// <summary>
        /// 修改工作区域的名称或者编码
        /// </summary>
        /// <param name="areaCode"></param>
        /// <param name="areaName"></param>
        public void ModifiyAreaInfo(string areaCode, string areaName)
        {
            AreaCode = string.IsNullOrEmpty(areaCode) ? string.Empty : areaCode;
            AreaName = string.IsNullOrEmpty(areaName) ? string.Empty : areaName;         
        }
    }
}