// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EES.Infrastructure.Entities;
using System;
using System.Collections.Generic;

namespace EES.Modules.Ums.Entities
{
    /// <summary>
    /// 用户 - 角色关系表
    /// </summary>
    public partial class UserRoles : EntityBase
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="userId">用户id</param>
        /// <param name="roleId">角色id</param>
        /// <param name="createUserId">创建者id</param>
        /// <param name="createUserName">创建这名字</param>
        public UserRoles(long userId, long roleId,long createUserId,string createUserName):base(createUserId, createUserName)
        {
            UserId = userId;
            RoleId = roleId;
        }

        /// <summary>
        /// 用户id
        /// </summary>
        public long UserId { get; private set; }

        /// <summary>
        /// 角色id
        /// </summary>
        public long RoleId { get; private set; }

        /// <summary>
        /// 用户
        /// </summary>
        public virtual User User { get; set; }

        /// <summary>
        /// 角色
        /// </summary>
        public virtual Role Role { get; set; }

        /// <summary>
        /// 生成实体
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="roleIds"></param>
        /// <param name="createUserId"></param>
        /// <param name="createUserName"></param>
        /// <returns></returns>
        public static IEnumerable<UserRoles> GenerateUserRoles(long userId,IEnumerable<long> roleIds, long createUserId, string createUserName) 
        {
            foreach (var roleId in roleIds)
            {
                yield return new UserRoles(userId, roleId, createUserId, createUserName);
            }
        }


    }
}